language: c++
sudo: required
matrix:
  include:
    - os: osx
      osx_image: xcode 8.3
      compiler: clang++
      addons:
        homebrew:
          packages:
           - pkg-config
           - glew
           - glm
           - opencv@2
           - ccache
          update: true
      before_install:
        - export PKG_CONFIG_PATH="/usr/local/opt/opencv@2/lib/pkgconfig"
        - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      script:
       - make
    - os: linux
      dist: trusty
      compiler: g++
      cache: ccache
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y libopencv-dev libglew-dev libglfw-dev libglm-dev libxxf86vm-dev
      script:
        - make
    - os: linux
      dist: xenial
      compiler: g++
      cache: ccache
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y libopencv-dev libglew-dev libglfw-dev libglm-dev libxxf86vm-dev
      script:
        - make
      after_success:
       - export CODECOV_TOKEN="ff73db72-4809-42e3-8298-2b6cdcc0e455"
       - gcov *.cpp
       - bash <(curl -s https://codecov.io/bash)
